name: checkout-build-run-docker
on:
  workflow_dispatch:
jobs:
  echo:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build docker images
        run: docker build -t signalr-template -f Dockerfile .
      - name: Run docker
        shell: 'script -q -e -c "bash {0}"'
        run: |
             docker run -it -p 5004:5004 --rm signalr-template
